var JskitSmartAD_VRoll_Data = [
	{
		"imgSrc":"../../model/ad/images/1.png",
		"text":"text1",
		"url":"#1",
		"alt":"alt1",
		"target":"_blank"
	}
	,{
		"imgSrc":"../../model/ad/images/2.png",
		"text":"text2",
		"url":"#2",
		"alt":"alt2",
		"target":"_blank"
	}
	,{
		"imgSrc":"../../model/ad/images/3.png",
		"text":"text3",
		"url":"#3",
		"alt":"alt3",
		"target":"_blank"
	}
	,{
		"imgSrc":"../../model/ad/images/4.png",
		"text":"text4",
		"url":"#4",
		"alt":"alt4",
		"target":"_blank"
	}
	,{
		"imgSrc":"../../model/ad/images/5.png",
		"text":"text5",
		"url":"#5",
		"alt":"alt5",
		"target":"_blank"
	}
];